### PR TITLE
fix forgotten QoS and Timestamp ext processing for query/reply

### PR DESCRIPTION
**Pull request by yellowhatter**
Issue #1107

### CODE REVIEW

**Comment by yellowhatter** [comment]
@Mallets @DariusIMP

**Comment by DariusIMP** [comment]
LGTM, I have tested it and it solves the issue.

However there is still another issue which may not be related (and I guess we can open a different issue for it) in which the priority is automatically set to Data despite specifying different values, both while doing a query and when replying to it.

**Review by DariusIMP — APPROVED** [review]

**Comment by Mallets** [comment]
If the priority is automatically set to Data despite specifying different values then I wonder wether the proposed changes are enough. I think also at API level `QoS` parameters should be mapped.

**Comment by yellowhatter** [comment]
Fixed bug in QoS bitfield. It affected ALL our QoS Priority in all the messages.

**Comment by DariusIMP** [comment]
Tested it and it works fine now! 👍

**Review by Mallets — APPROVED** [review]

**Pull request merged**
