### PR TITLE
feat: unify pub/sub and query/reply modules

### PR DESCRIPTION
**Pull request by wyfo**

### CODE REVIEW

**Comment by wyfo** [comment]
@Mallets @kydos @milyin

**Comment by wyfo** [comment]
I've let the `core` module as is for now. Maybe we should create a `qos` module to put QOS  related things (`Priority` and `CongestionControl` for now, but maybe more later), as they are common to pub/sub and query/reply.

**Comment by wyfo** [comment]
About `Encoding`, I'm hesitating to put it in `core` with `Priority` and `CongestionControl`, but it may also be put in `bytes` module, as this is closely related. I think I prefer this solution now.

**Comment by Mallets** [comment]
@wyfo it would be great if this PR comes with a battery of sister PRs to update all bindings/plugins/backends with the new module organization.

**Comment by wyfo** [comment]
This is incredibly long to patch all backend/plugins, so I've written a Python script to modify the imports automatically 😅

**Comment by wyfo** [comment]
@Mallets All the sister PRs have been opened.

**Review by Mallets — APPROVED** [review]

**Review by Mallets — APPROVED** [review]

**Pull request merged**
