### PR TITLE
make examples SHM-agnostic

### PR DESCRIPTION
**Pull request by yellowhatter**
I adopt examples to illustrate that SHM operation is transparent at data reception side. For example, I removed `z_sub_shm` and instead `z_sub` will print out SHM datatype for SHM buffers if it is compiled with SHM support

### CODE REVIEW

**Comment by yellowhatter** [comment]
@Mallets

**Comment by Mallets** [comment]
I believe the proposed changes obfuscate the examples rather than clarifying them... Taking out some critical Zenoh code from the example and put it in a common module (`receive_sample`) and using it directly makes the example hard to read and follow.
Moreover, changing the output format has an impact on interoperability tests, which should be updated accordingly. 
Therefore, I'm rather against merging this PR,

**Comment by yellowhatter** [comment]
> I believe the proposed changes obfuscate the examples rather than clarifying them... Taking out some critical Zenoh code from the example and put it in a common module (`receive_sample`) and using it directly makes the example hard to read and follow. Moreover, changing the output format has an impact on interoperability tests, which should be updated accordingly. Therefore, I'm rather against merging this PR,

The main goal of this PR is to illustrate that Zenoh works with SHM data in transparent manner and also to reduce the number of examples by removing excessive `z_sub_shm`.

So, for readability we can remove the common code block and put it into examples directly, but the output format change is necessary as it now indicates SHM type info, that is also a subject for interoperability tests, thus worth supporting there.

**Comment by Mallets** [comment]
SHM is not available in all languages, so it's a no go for the time being to modify all bindings to support something that is available only in Rust, C, and C++. Let's keep `z_sub` and `z_pub` simple and let's add anything related to `shm` into `shm` example for the time being.

Although SHM is an extremely cool feature of Zenoh, not every user nor beginner will use it. So, my advise is not to make simply things more complex. Moreover, if we plan to change basic examples, the PR should come with sister PRs that update base interoperability tests.

**Pull request closed without merging**
