### PR TITLE
zenohd-default config error #1292

### PR DESCRIPTION
**Pull request by anhaabaete**
zenohd default config error #1292

### CODE REVIEW

**Comment by anhaabaete** [comment]
basta apenas fazer o login no eclipse ?

**Comment by Mallets** [comment]
Before merging this PR you should sign the Eclipse ECA [here](https://api.eclipse.org/git/eca/status/gh/eclipse-zenoh/zenoh/1298). Make sure you use the same email address you used on GitHub for the PR.

**Comment by anhaabaete** [comment]
> Before merging this PR you should sign the Eclipse ECA [here](https://api.eclipse.org/git/eca/status/gh/eclipse-zenoh/zenoh/1298). Make sure you use the same email address you used on GitHub for the PR.

I Accept all terms. I need remake the PR?

**Comment by Mallets** [comment]
> I Accept all terms. I need remake the PR?

Thanks! No need to remake the PR, an empty commit on this PR will suffice to retrigger the CI.

**Review by anhaabaete — COMMENTED** [review]
Ok

**Comment by gabrik** [comment]
Hi @anhaabaete can you please fix the typo identified by the CI: https://github.com/eclipse-zenoh/zenoh/actions/runs/10312240438/job/28553183850?pr=1298 ?

**Comment by anhaabaete** [comment]
@Mallets @gabrik 

I saw problems test. All it's about a downsample, but I change the start set config. It don't have relationship with downsample. How what real problem?

thanks!

**Pull request merged**
