### PR TITLE
Rename `close` to `undeclare` in `zenoh-ext`

### LINKED ISSUE #1285: `PublicationCache::close` and `FetchSubscriber::close` should be named `undeclare`
### Describe the feature

This is to align the naming convention with the `zenoh` crate.

### PR DESCRIPTION
**Pull request by fuzzypixelz**
Fixes #1285.

### CODE REVIEW

**Review by Mallets — APPROVED** [review]
Before merging it is necessary to check wether these functions are used in `zenoh-c`.
If yes, then a sister PR should be open.

**Comment by fuzzypixelz** [comment]
> Before merging it is necessary to check wether these functions are used in `zenoh-c`. If yes, then a sister PR should be open.

You're right, both are used. But we need this merged first before I can reference the merge commit in the lockfile.

**Comment by Mallets** [comment]
> > Before merging it is necessary to check wether these functions are used in `zenoh-c`. If yes, then a sister PR should be open.
> 
> You're right, both are used. But we need this merged first before I can reference the merge commit in the lockfile.

The good way to proceed is to minimize the misalignment window between repos as much as possible. It would be good to have the CI running already on zenoh-c pointing to this branch. If the CI in zenoh-c is passing then we can quickly merge this PR and point zenoh-c's PR to `dev/1.0.0`.

**Comment by fuzzypixelz** [comment]
@Mallets Ready to merge.

**Pull request merged**
