### PR TITLE
Fix cli examples

### PR DESCRIPTION
**Pull request by Jarsop**
Some mistakes are present in CLI examples, this PR attempts to fix it.

BTW thanks for your awesome work ! :crown:

### CODE REVIEW

**Review by kydos — APPROVED** [review]
Looks good, thanks for your contribution!

**Comment by fuzzypixelz** [comment]
Hi! Good catch :)

You seems to have missed a few incorrect downcasts to `&String` in `ArgMatches::get_many` and `ArgMatches::get_one` calls. You can try something like `rg 'get_.*::<&String>' .` to get all of them.

**Comment by kydos** [comment]
Thanks for you PR @Jarsop.

**Comment by Jarsop** [comment]
> Hi! Good catch :)
> 
> You seems to have missed a few incorrect downcasts to `&String` in `ArgMatches::get_many` and `ArgMatches::get_one` calls. You can try something like `rg 'get_.*::<&String>' .` to get all of them.

@fuzzypixelz yes I've seen other downcasts but as it's optional arguments, when you request `get_*::<&String>()` it converts to `Option<&String>` which is valid. I ran all the examples to see where there was this downcast problem and normally everything is fine but maybe I missed something :)

**Pull request merged**
