### PR TITLE
Update depdendencies

### PR DESCRIPTION
**Pull request by fuzzypixelz**
Not much to say here.

### CODE REVIEW

**Comment by Mallets** [comment]
@fuzzypixelz can we make sure the change is reflected in the `Cargo.toml` as well?

**Comment by fuzzypixelz** [comment]
@Mallets The `Cargo.toml` specify version ranges, this pull request bumps dependencies within those ranges.

For example tokio has been bumped from `1.39.3` to `1.40.0` because in `Cargo.toml` we got `tokio = "1.39.3"` and that means any `1.x.y` version where `x >= 39` and `y >= 3`.

Same goes for tokio-util which went from `0.7.11` to `0.7.12`.

Updating the `Cargo.toml` is only necessary if we go through semver-incompatible changes, which is beyond the scope of this pull request.

**Comment by Mallets** [comment]
It should be in the scope of the next `-rc` for Zenoh. Even though `cargo` does what you described, it would be good to have the version bumped and verify that Zenoh depends on the very latest crates.

**Comment by fuzzypixelz** [comment]
@Mallets Done.

**Review by Mallets — APPROVED** [review]

**Pull request merged**
