### PR TITLE
test for drop session of same runtime

### PR DESCRIPTION
**Pull request by milyin**
Test for creating and dropping session from Runtime

### CODE REVIEW

**Comment by fuzzypixelz** [comment]
@milyin Please change your pull request's base branch to main (new default branch). And rebase your branch against `main` as it is missing a status check necessary to merge this pull request but which is only available on `main`.

**Comment by Mallets** [comment]
@milyin this PR is still marked as Draft and pointing to master. Is it relevant?

**Comment by imstevenpmwork** [comment]
@milyin ping for Mallet's question

**Comment by milyin** [comment]
Yes, it's relevant. This is a test for bug https://github.com/eclipse-zenoh/zenoh/issues/612 - currently it should fail, so it doesn't make sense to merge it

**Comment by milyin** [comment]
The code in this PR is merged as part of https://github.com/eclipse-zenoh/zenoh/pull/917

**Pull request closed without merging**
