### PR TITLE
Compile on stable

### PR DESCRIPTION
**Pull request by bfrog**
Compile against stable rather than nightly

### CODE REVIEW

**Comment by bfrog** [comment]
It compiles, and most tests pass, I haven't compared against the normal sync branch to see if the same tests fail yet

**Comment by Mallets** [comment]
Hello @bfrog ! Thanks for submitting the pull request. The CI seems to fail because the `rust-toolchain` file has been removed and it is required by the CI workflow.

Could you just restore the `rust-toolchain` fail and set its content to `stable`?

**Comment by Mallets** [comment]
The CI is failing because of code format. 

Can you please run the following:
- `cargo fmt`
- `cargo clippy`

You shouldn't see any warning with those two commands.
Then `cargo test` should succeed according to your changes.

**Comment by bfrog** [comment]
Clippy reported errors not related to my changes from what I could tell, ran cargo fmt

**Comment by bfrog** [comment]
I did verify that net::session::Session::declare_callback_subscriber fails on both sync and this branch so its not a change I made that causes that particular test failure.

**Comment by Mallets** [comment]
It seems the clippy error you were seeing was solved after you forked the zenoh repo. 
The checks have all successfully passed so I have just merged the PR!
Thank you very much for contributing this, being able to compile zenoh in stable it's certainly a great plus!

**Pull request merged**
