### PR TITLE
fix for issue 273: sort/dedup using BTreeMap

### PR DESCRIPTION
**Pull request by milyin**
Here is a fix for https://github.com/eclipse-zenoh/zenoh/issues/273 issue. ```Vec``` has been replaced to ```BTreeMap``` which allows to sort/dedup samples on the fly.
This code is not covered with unit tests, but sample z_query_sub seems to work ok. Any recommendations how to run performance test to check is this update actually useful are appreciated

### CODE REVIEW

**Comment by Mallets** [comment]
Hello @milyin , 

thanks a lot for your contribution!

In order for us to accept any PR, you would need to sign the Eclipse contribution agreement [here]( https://accounts.eclipse.org/user/login?destination=legal/eca/validation/111441).

Finally, would you be so kind to rebase to latest master branch? 
Clippy has been updated in the recent days and now is throwing more warnings that make the CI fail.
We have already fixed it in master and this would allow to have all tests to pass before merging.

**Comment by JEnoch** [comment]
Hi @milyin ,

Thanks for your contribution!

> Finally, would you be so kind to rebase to latest master branch?

Actually, we already made important changes in the QueryingSubscriber in the [api-changes](https://github.com/eclipse-zenoh/zenoh/tree/api-changes) branch. This branch will soon be merged to master.
It would be perfect if you can rather create a new PR on the api-changes branch ! 😃

**Comment by milyin** [comment]
@Mallets , @JEnoch thank you for comments. Made request for api-changes branch https://github.com/eclipse-zenoh/zenoh/pull/287

**Comment by Mallets** [comment]
Closing this issue since #287 has been merged into `api-changes` branch.

**Pull request closed without merging**
