### PR TITLE
feat!: move serialization into zenoh-ext

### PR DESCRIPTION
**Pull request by wyfo**
@kydos @DenisBiryukov91

### CODE REVIEW

**Comment by milyin** [comment]
I like the proposed solution. And maybe it can be made even simpler. It seems that we don't need to put this to zenoh-ext. One of our goals is to explicitly detach serialization from `ZBytes`. But serialization in any case will be present in all bindings. Moving it to zenoh-ext doesn't change a lot.
Instead the traits `ZBytesExt`, `ZBytesWriterExt` which attaches serialization to `ZBytes` can be removed without losing functionality. We already have all necessary functionality in `Serialize` and `Deserialize` traits and may allow user to use them directly.

My proposal is to define `Serialize` in zenoh and make it something like this:
```rust
pub trait Serialize {
    fn serialize(&self, writer: &mut ZBytesWriter);
    fn serialize_iter<I: IntoIterator<Item = &Self>>(iter: I, writer: &mut ZBytesWriter) where I::IntoIter: ExactSizeIterator {
        let iter = iter.into_iter();
        self.write_vle(iter.len() as u64);
        for t in iter {
            t.serialize(self);
        }
   }
   fn into_zbytes(self) -> ZBytes;
   fn into_zbytes_iter< ......
}
```

The idea is that `ZBytes` is not aware at all about serialization. Instead each type can implement the `Serialize` and `Deserialize` traits and use the methods directly:

```
    let mut bytes = ZBytes::new();
    let mut writer = bytes.writer();
    let i1 = 1234_u32;
    let i2 = String::from("test");
    let i3 = vec![1, 2, 3, 4];
    i1.serialize(&mut writer);
    i2.serialize(&mut writer);
    i3.serialize(&mut writer);
    // deserialization
    let mut reader = bytes.reader();
    let o1 = u32::deserialize(&mut reader).unwrap();
    let o2 = String::deserialize(&mut reader).unwrap();
    let o3 = Vec::<u8>::deserialize(&mut reader).unwrap();
```

**Comment by wyfo** [comment]
There are two issues with your proposal:
- `serialize_iter` shouldn't be a trait method, because otherwise it would be meant to be overridden, and that's not the case;
- my previous draft was in fact using method on the (de)serialized type instead of the writer/reader, but @DenisBiryukov91 was against it.

**Comment by milyin** [comment]
> There are two issues with your proposal:
> 
>     * `serialize_iter` shouldn't be a trait method, because otherwise it would be meant to be overridden, and that's not the case;
Ok, then it should be real method, no problem

>     * my previous draft was in fact using method on the (de)serialized type instead of the writer/reader, but @DenisBiryukov91 was against it.

@DenisBiryukov91 mentioned that the code looks ugly from his point of view. But I think the full separation of serialization and writer worths it. The visible fact that there is no connection from writer to serializer will really help user get the idea, where is the base functionality and where is the replaceable helper

**Comment by wyfo** [comment]
Superseded by #1473

**Pull request closed without merging**
