### PR TITLE
Bypassing error while performing recv_from in orchestrator.rs.

### PR DESCRIPTION
**Pull request by adlinknorm**
Without bypassing the error, scouting under Windows will lead to remote zenoh instance terminating.
Basic testing under Windows 10 x64 is done and didn't get any problem after fix.

Changes to be committed:
	modified:   zenoh/src/net/runtime/orchestrator.rs

### CODE REVIEW

**Comment by Mallets** [comment]
Hi @adlinknorm,

Thanks for your PR. In order to merge it I need you to sign the Eclipse ECA: https://accounts.eclipse.org/legal/eca/validation/97214.

Once this is done, we can move forward with the review of your PR.
@OlivierHecart can you have a look at it?

**Comment by adlinknorm** [comment]
Hi @Mallets,
The work is based on @OlivierHecart's code and suggestion (to also log error rather than just bypassing error).
If Olivier is OK with with me signing the ECA. I will do the signing right away.
Or feel free to simply integrate the code (three lines of code) by Olivier directly. Thanks a lot!

**Comment by Mallets** [comment]
Hi @adlinknorm ,

Then please sign the Eclipse ECA and we will be happy merge your PR :)

**Comment by adlinknorm** [comment]
Hi @Mallets,
I have signed the Eclipse ECA. Thanks! :)

**Comment by Mallets** [comment]
The CI is failing complaining that code is not correctly formatted.
Please run `cargo fmt --all` and update the PR.

**Comment by adlinknorm** [comment]
I have updated the format, thanks!

**Pull request merged**
