### PR TITLE
fix: make rx task close the link properly in low-latency transport

### LINKED ISSUE #1024: Zenoh fails to reconnect when running with `lowlatency` and without scouting/gossip
### Describe the bug

I'm running pub/sub example, meant for servers running in production. Multicast and gossip expose more risk, so they are disabled. I'm have trouble reconnecting after the publisher restarts when in `low_latency` mode. 

### To reproduce

Please see this diff: https://github.com/eclipse-zenoh/zenoh/compare/0.11.0-rc.2...jito-labs:zenoh:eric/bug-repro?expand=1

1. Start Publisher on machine 1
2. Start Subscriber on machine 2, let it receive messages
3. Restart Publisher on machine 1
4. Subscriber never reconnects

### System info

Arch, linux 6.6.28-1-lts
Rust version: using default in toolchain file

### PR DESCRIPTION
**Pull request by YuanYuYuan**
Closes #1024.

### CODE REVIEW

**Comment by esemeniuc** [comment]
Tested this branch with udp (no `lowlatency` settings), still misses connections

**Comment by esemeniuc** [comment]
TCP with lowlatency looks good

**Comment by Mallets** [comment]
@yellowhatter could you please have a look at this PR?

**Review by yellowhatter — APPROVED** [review]
Looks good!

**Pull request merged**
