### PR TITLE
Use .readthedocs.yaml for building ReadTheDocs's content. 

### PR DESCRIPTION
**Pull request by evshary**
RTD requests the migration of configuration v2:
https://blog.readthedocs.com/migrate-configuration-v2/

### CODE REVIEW

**Comment by p-avital** [comment]
@Mallets have we even used ReadTheDocs with Zenoh ever since 0.5? If not, we could just drop it entirely, since `docs.rs` is our canon doc for zenoh-rs

**Comment by Mallets** [comment]
> @Mallets have we even used ReadTheDocs with Zenoh ever since 0.5? If not, we could just drop it entirely, since `docs.rs` is our canon doc for zenoh-rs

We can drop `ReadTheDocs` entirely and use only `docs.rs`.

**Comment by p-avital** [comment]
@evshary since you've already made this PR on the subject: do you mind repurposing it to remove the RTD stuff from the repo? :)

**Comment by evshary** [comment]
Sure, then I'll remove all `zenoh/docs` folder directly.

**Review by p-avital — APPROVED** [review]

**Pull request merged**
