### PR TITLE
Add note about Rust nightly

### PR DESCRIPTION
**Pull request by esteve**
Add note about Rust nightly

### CODE REVIEW

**Comment by esteve** [comment]
@kydos I've signed up, but every time I submit my ECA I get the same error:

"Error message
Error, An error has occured and your Eclipse Contributor Agreement was not submitted. (ECA-04)"

I'll try again in a few minutes.

**Comment by esteve** [comment]
@kydos here's a screenshot of the error:

image

My username is efernandez140. I first signed up with my GMail address, but then changed it to the Apache one (esteve (at) apache (dot) org) because my commits are done with the latter.

**Comment by JEnoch** [comment]
@esteve : looking in the ECA validation tool (https://accounts.eclipse.org/users/efernandez140/eca for you) neither your GMail or Apache address is attached to a valid ECA. I think you should update or re-apply the ECA on this same page.

**Comment by esteve** [comment]
@JEnoch that's the webpage I used to sign the ECA, but unfortunately every time I try I get the same error. @kydos has kindly raised this issue at Eclipse

**Pull request merged**
