### PR TITLE
Removed trailing whitespace

### PR DESCRIPTION
**Pull request by esteve**
While examining the source code I found a few places where there was trailing whitespace. I don't know if that was intended, but here's a PR that cleans that up.

### CODE REVIEW

**Comment by kydos** [comment]
There still seems to be an issue with the ECA.

**Comment by esteve** [comment]
@kydos the ECA issue looks like it got fixed, I revalidated it yesterday and the check passes

**Comment by kydos** [comment]
@esteve  can you please take a look at the conflicts?

**Comment by esteve** [comment]
@kydos fixed. Most of the trailing whitespace is gone with `rustfmt`, but there's a few in the C part and in the comments in the Rust code.

**Pull request merged**
