### PR TITLE
Zenoh: Fix badly behaved build.rs scripts.

### PR DESCRIPTION
**Pull request by chachi**
build.rs should only ever modify OUT_DIR. These scripts were modifying local files which caused a git index update which caused them to rebuild due to the git-version appearing out of date.

### CODE REVIEW

**Comment by J-Loudet** [comment]
Thanks for your contribution @chachi!
This looks good to me, if you could fix the formatting issue (by running and committing the result of `cargo fmt`) I would then be able to merge.

**Review by J-Loudet — CHANGES_REQUESTED** [review]
LGTM 👍
Please run `cargo fmt` and commit the changes.

**Comment by chachi** [comment]
Fixed!

**Comment by J-Loudet** [comment]
Hi @chachi, thanks for the fix.
It turns out I did not fully grasp the purpose of these `build.rs` files, they not only validate the `config.json5` but also update the content of `config_schema.json5`.

This is, as you pointed out, not a recommended practice which led to some internal issues: #897 
However I am not sure of the course of action.

@milyin @fuzzypixelz what's your take?

**Comment by fuzzypixelz** [comment]
> Hi @chachi, thanks for the fix. It turns out I did not fully grasp the purpose of these `build.rs` files, they not only validate the `config.json5` but also update the content of `config_schema.json5`.
> 
> This is, as you pointed out, not a recommended practice which led to some internal issues: #897 However I am not sure of the course of action.
> 
> @milyin @fuzzypixelz what's your take?

I would either:

1. Remove the code that read/writes `config_schema.json5` (in this PR it's a no-op)
2. Assert that `config_schema.json5` conforms to `config::Config` without actually overriding it with the correct value

**Comment by chachi** [comment]
No problem. Let me know if I should make any changes to this PR or you'd like to take it from here. Happy to help!

**Comment by fuzzypixelz** [comment]
> No problem. Let me know if I should make any changes to this PR or you'd like to take it from here. Happy to help!

Yes, please do update this PR if you can.

I suggest going with option (2), failing the build when the config schema file doesn't match the `Config` structure.

**Comment by J-Loudet** [comment]
See #939

**Pull request closed without merging**
