### PR TITLE
refactor(tracing): Using `tracing` instead of `log` for logging

### LINKED ISSUE #894: [Refactor] Replace `log` by `tracing`
### Describe the release item

Move al logging from the `log` crate to the `tracing` crate.

### PR DESCRIPTION
**Pull request by gabrik**
Replacing `log` with `tracing` and `env_logger` with `tracing_subscriber`.

Added `init_log()` function to `zenoh_util` as init tracing logging is a bit more complicated than `env_logger::init()` 

Bindings Sister PRs:
- Python: https://github.com/eclipse-zenoh/zenoh-python/pull/172
- C: https://github.com/eclipse-zenoh/zenoh-c/pull/308
- Java: https://github.com/eclipse-zenoh/zenoh-java/pull/58
- Kotlin: https://github.com/eclipse-zenoh/zenoh-kotlin/pull/63

Plugins/Backends Sister PRs:
- MQTT: https://github.com/eclipse-zenoh/zenoh-plugin-mqtt/pull/67
- DDS: https://github.com/eclipse-zenoh/zenoh-plugin-dds/pull/204
- ROS2DDS: https://github.com/eclipse-zenoh/zenoh-plugin-ros2dds/pull/105
- FileSystem: https://github.com/eclipse-zenoh/zenoh-backend-filesystem/pull/82
- InfluxDB: https://github.com/eclipse-zenoh/zenoh-backend-influxdb/pull/92
- RocksDB: https://github.com/eclipse-zenoh/zenoh-backend-rocksdb/pull/70
- S3: https://github.com/eclipse-zenoh/zenoh-backend-s3/pull/45
- ROS1: https://github.com/eclipse-zenoh/zenoh-plugin-ros1/pull/49
- Webserver: https://github.com/eclipse-zenoh/zenoh-plugin-webserver/pull/58

Closes #894

### CODE REVIEW

**Comment by gabrik** [comment]
Closes #894

**Comment by gabrik** [comment]
@Mallets sister PRs have been created, did I miss some repo?

**Comment by gabrik** [comment]
Leak could depend on this: https://github.com/tokio-rs/tracing/issues/2069

Maybe `lazy_static!` for initialization?

**Comment by gabrik** [comment]
@DenisBiryukov91 can you check if the this memory leak is acceptable?

**Comment by DenisBiryukov91** [comment]
The leeks indeed seem to come from tracing (originated from zenoh_utils::init_log). But I do not think we should consider any memory leaks as acceptable, unless we provide the user a (possibly unsafe)  way to avoid them. Would it be possible to implement a log_close method similarly to what was done for ZRuntimePool drop / ZRuntimePoolGuard  in zenoh-runtime ?

**Comment by gabrik** [comment]
Maybe it is possible, but I do not thing it can be done in Zenoh, I think it has to be done in `tracing`.

The issue there is the `tracing::subscriber::set_global_default(subscriber)` creating a static inside `tracing`.

Even is we "drop" the result of the call the subscriber will still be there, unless we plan to contribute something to tracing.

**Comment by gabrik** [comment]
It has to be done in `tracing` if we want, the code that initialized the static is this [here](https://github.com/tokio-rs/tracing/blob/master/tracing-core/src/dispatch.rs#L331C8-L331C26)

**Comment by DenisBiryukov91** [comment]
There is a public function [get_current](https://github.com/tokio-rs/tracing/blob/908cc432a5994f6e17c8f36e13c217dc40085704/tracing-core/src/dispatch.rs#L490),
that allows to apply a function to a global subscriber. 
With a bit of unsafe black magic it should be possible to delete it.

**Comment by gabrik** [comment]
> will the tests pass if you do not call zenoh_utils::init_log() in the beginning of main, or initialize a logger with NoSubscriber ?

Yes on my machine the valgrind test passes without the call to `init_log`

**Comment by gabrik** [comment]
For reference:

| zenohd  | Size  (bytes)| diff
|---|---|---|
| `log`  | 17112192  | - |
|  `tracing` |  18826744 |1714552 |

Using tracing makes `zenohd` binary  **1.7MB** bigger, @JEnoch is this acceptable?

**Comment by gabrik** [comment]
For reference:

via `z_pub_thr` and `z_sub_thr` examples

| pub/sub (thr)  | msgs| diff | net |
|---|---|---|---|
| `log`  (main)|  3963062  | - | localhost |
|  `tracing` |  3812013 | -151049 | localhost |
| `log`  (main)|  3998883  | - | 100gbe |
|  `tracing` | 3798591  |  -200292 | 100gbe |
 
 
@Mallets this is worrying...

**Comment by gabrik** [comment]
with `RUSTFLAGS='-C target-cpu=native'` the situation is better.

```
+-------------------------+----------+----------+
|        pub/sub          |  msgs    |   diff   |
+-------------------------+----------+----------+
| log                     | 3956274  |        - |
| tracing                 | 4103986  |  147712  |
+-------------------------+----------+----------+
```

**Comment by YuanYuYuan** [comment]
## P2P Results on C17

### Latency

```txt

| Protocol      |   5th Percentile |   Median |   95th Percentile |
|:--------------|-----------------:|---------:|------------------:|
| P2P (main)    |             10.0 |     10.0 |              10.0 |
| P2P (tracing) |             10.0 |     10.0 |              10.0 |
```
latency

### Throughput

```txt
| Payload size   | P2P (main)   | P2P (tracing)   |
|:---------------|:-------------|:----------------|
| 8 B            | 236.3 M      | 257.8 M         |
| 16 B           | 474.2 M      | 487.2 M         |
| 32 B           | 944.8 M      | 947.9 M         |
| 64 B           | 1.9 G        | 2.0 G           |
| 128 B          | 3.6 G        | 3.9 G           |
| 256 B          | 7.3 G        | 7.4 G           |
| 512 B          | 13.1 G       | 13.7 G          |
| 1 KB           | 23.7 G       | 23.4 G          |
| 2 KB           | 37.9 G       | 39.9 G          |
| 4 KB           | 59.6 G       | 58.0 G          |
| 8 KB           | 61.7 G       | 61.9 G          |
| 16 KB          | 54.7 G       | 54.9 G          |
| 32 KB          | 43.2 G       | 43.6 G          |
| 64 KB          | 38.1 G       | 39.8 G          |
| 128 KB         | 41.8 G       | 42.5 G          |
| 256 KB         | 47.0 G       | 46.6 G          |
| 512 KB         | 40.1 G       | 38.3 G          |
| 1 MB           | 46.7 G       | 48.5 G          |
| 2 MB           | 35.4 G       | 35.0 G          |
| 4 MB           | 32.1 G       | 50.8 G          |
| 8 MB           | 29.0 G       | 29.4 G          |
| 16 MB          | 56.7 G       | 27.9 G          |
| 32 MB          | 53.5 G       | 40.2 G          |
| 64 MB          | 59.5 G       | 57.9 G          |
| 128 MB         | 59.0 G       | 56.8 G          |
| 256 MB         | 49.3 G       | 51.5 G          |
| 256 MB         | 53.6 G       | 53.6 G          |
| 512 MB         | 51.5 G       | 51.5 G          |
```

bit_per_second

**Comment by gabrik** [comment]
Adding a `init_log` function that does not "leak", and renamed the previous one in `init_log_from_env`

The new one is being used in the Valgrind tests.

**Review by Mallets — APPROVED** [review]

**Pull request merged**
