### PR TITLE
do not use Linux Ephemeral ports in tests

### PR DESCRIPTION
**Pull request by yellowhatter**
Sometimes this causes tests to fail because of port collision

### CODE REVIEW

**Comment by oteffahi** [comment]
@yellowhatter could you please also update the port numbers in these tests: https://github.com/eclipse-zenoh/zenoh/blob/main/zenoh/tests/authentication.rs#L44-L81
Please respect the unicity of ports as it is, quic and tls do not close their ports in a consistent time, and the different tests run concurrently
Thanks 😄

**Comment by yellowhatter** [comment]
> @yellowhatter could you please also update the port numbers in these tests: https://github.com/eclipse-zenoh/zenoh/blob/main/zenoh/tests/authentication.rs#L44-L81 Please respect the unicity of ports as it is, quic and tls do not close their ports in a consistent time, and the different tests run concurrently Thanks 😄

Yep, my text search wasn't good enough to find also these ports ;)

**Comment by yellowhatter** [comment]
@oteffahi done

**Review by oteffahi — APPROVED** [review]
LGTM.

**Pull request merged**
