### PR TITLE
chore: enable rest plugin only if in config or if --rest-http-port is set

### PR DESCRIPTION
**Pull request by gabrik**
Currently the rest plugin is enabled by default for `zenohd`, which means that its a required dependency when running a simple zenoh router without configuration.

This PR changes the behaviour by enabling the rest plugin only if the `--rest-http-port` is passed.

### CODE REVIEW

**Comment by OlivierHecart** [comment]
Should be:
```rust
    // apply '--rest-http-port' to config only if explicitly set (overwriting config)
    if args.rest_http_port.is_some() || args.config.is_none() {
        match args.rest_http_port.as_deref() {
            Some(value) => {
                if !value.eq_ignore_ascii_case("none") {
                    config
                        .insert_json5("plugins/rest/http_port", &format!(r#""{value}""#))
                        .unwrap();
                    config
                        .insert_json5("plugins/rest/__required__", "true")
                        .unwrap();
                }
            }
            None => {
                config
                    .insert_json5("plugins/rest/http_port", "8000")
                    .unwrap();
            }
        }
    }
```

**Comment by gabrik** [comment]
shouldn't the `|| args.config.is_none()` be removed to load only if the argument passed?

**Comment by gabrik** [comment]
> > shouldn't the `|| args.config.is_none()` be removed to load only if the argument passed?
> 
> Well the point is that we want rest to start on port 8000 by default if nothing is specified.

the point of my PR is not not have it unless `--rest-http-port` is specified

**Comment by OlivierHecart** [comment]
> > > shouldn't the `|| args.config.is_none()` be removed to load only if the argument passed?
> > 
> > 
> > Well the point is that we want rest to start on port 8000 by default if nothing is specified.
> 
> the point of my PR is not not have it unless `--rest-http-port` is specified

I believed the point of the PR was to not fail if rest was not available but still start it on port 8000 by default if available.

**Comment by Mallets** [comment]
I agree with this PR and not having unnecessary services running if not specified. 
Moreover, with current status it's impossible to compile and run `zenohd` without forcing the compilation of the `rest plugin`, which is quite annoying tbh.
The PR should also include updates to the README to explicitly set the `--http-port` parameter when needed.

**Comment by Mallets** [comment]
Documentation to be updated: https://zenoh.io/docs/manual/configuration/ 
Dockerfile to be updated: https://github.com/eclipse-zenoh/ci/blob/7cbe301bce9b932eea7ffea2b463890ab712f97e/publish-crates-docker/Dockerfile#L14

**Comment by gabrik** [comment]
> * [ ]  Documentation to be updated: https://zenoh.io/docs/manual/configuration/ [Explicit mention zenohd --http-rest-port in documentation atolab/zenoh-web#88](https://github.com/atolab/zenoh-web/pull/88)
> 
> 
> Update: ~Dockerfile to be updated: https://github.com/eclipse-zenoh/ci/blob/7cbe301bce9b932eea7ffea2b463890ab712f97e/publish-crates-docker/Dockerfile#L14~ Current Dockerfile already passes all CLI arguments to the inner `zenohd`. So no new changes are expected.
> 
> @gabrik this PR is complete from PoV. Anything else?

Looks good to me.

**Comment by JEnoch** [comment]
We have examples of REST API usage in backends READMEs that shall be updated with the correct `zenohd` command line for REST plugin activation:
* [ ] https://github.com/eclipse-zenoh/zenoh-backend-influxdb?tab=readme-ov-file#setup-at-runtime-via-curl-commands-on-the-admin-space
* [ ] https://github.com/eclipse-zenoh/zenoh-backend-rocksdb?tab=readme-ov-file#setup-at-runtime-via-curl-commands-on-the-admin-space
* [ ] https://github.com/eclipse-zenoh/zenoh-backend-filesystem?tab=readme-ov-file#setup-at-runtime-via-curl-commands-on-the-admin-space

**Review by Mallets — APPROVED** [review]

**Comment by alex-quilt** [comment]
From https://github.com/eclipse-zenoh/zenoh/issues/1031, https://zenoh.io/docs/getting-started/quick-test/ should also be updated since the instructions currently don't work

**Pull request merged**
